import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { motion, AnimatePresence } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "PI5",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "bg-gray-100"}>{children}</body>
    </html>
  );
}
